import scrapy

class MovieItem(scrapy.Item):
    title = scrapy.Field()
    originalTitle = scrapy.Field()
    alias = scrapy.Field()
    type = scrapy.Field()
    category = scrapy.Field()
    year = scrapy.Field()
    area = scrapy.Field()
    language = scrapy.Field()
    cover = scrapy.Field()
    poster = scrapy.Field()
    director = scrapy.Field()
    actor = scrapy.Field()
    writer = scrapy.Field()
    description = scrapy.Field()
    rating = scrapy.Field()
    status = scrapy.Field()
    totalEpisodes = scrapy.Field()
    currentEpisode = scrapy.Field()
    updateSchedule = scrapy.Field()
    duration = scrapy.Field()
    sources = scrapy.Field()
    tags = scrapy.Field()
    spiderSource = scrapy.Field()
    spiderUrl = scrapy.Field()
